import { Edit3, FileText, House, Link as LinkIcon, Trash2, Wrench } from 'lucide-react'
import { Link } from 'react-router'
import type { AppState } from '@/store/app-state'
import type { FinancialTransaction } from '@/domain/types'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { formatCurrencyBRL } from '@/lib/utils'
import { formatFinancialDate, getCategoryLabel, getTransactionStatusLabel, getTransactionTypeLabel } from '@/features/financial/presentation'

function TransactionDetails({ transaction, state, confirmingDelete, onClose, onEdit, onAskDelete, onCancelDelete, onDelete }: { transaction: FinancialTransaction; state: AppState; confirmingDelete: boolean; onClose: () => void; onEdit: () => void; onAskDelete: () => void; onCancelDelete: () => void; onDelete: () => void }) {
  const chapter = state.chapters.find(item => item.id === transaction.chapterId)
  const documents = state.documents.filter(item => transaction.documentIds.includes(item.id))
  const asset = state.assets.find(item => item.id === transaction.assetId)
  const maintenance = state.maintenanceRecords.find(item => item.id === transaction.maintenanceId)
  return <Card className="border-primary/20 shadow-book-sm"><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle className="font-display text-xl">Detalhes da movimentação</CardTitle><p className="mt-1 text-sm text-muted-foreground">{transaction.title || 'Movimentação sem título'}</p></div><Button type="button" variant="ghost" size="sm" onClick={onClose}>Fechar</Button></div></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">Valor</p><p className="mt-1 font-semibold">{formatCurrencyBRL(Number.isFinite(transaction.amount) ? transaction.amount : 0)}</p></div><div><p className="text-xs text-muted-foreground">Data</p><p className="mt-1 font-medium">{formatFinancialDate(transaction.date)}</p></div><div><p className="text-xs text-muted-foreground">Categoria</p><p className="mt-1 font-medium">{getCategoryLabel(transaction.category)}</p></div><div><p className="text-xs text-muted-foreground">Status e tipo</p><p className="mt-1"><Badge variant="secondary">{getTransactionStatusLabel(transaction.status)}</Badge> <span className="ml-1">{getTransactionTypeLabel(transaction.type)}</span></p></div></div>{transaction.description ? <p className="border-t pt-4 text-sm leading-relaxed text-muted-foreground">{transaction.description}</p> : null}<div className="grid gap-2 text-sm sm:grid-cols-2">{chapter ? <Link to={`/livro-da-casa/${chapter.id}`} className="flex items-center gap-2 text-primary hover:underline"><LinkIcon className="size-4" />{chapter.title}</Link> : transaction.chapterId ? <p className="text-muted-foreground">Capítulo relacionado não disponível</p> : null}{documents.map(document => <p key={document.id} className="flex items-center gap-2"><FileText className="size-4 text-primary" />{document.name}</p>)}{asset ? <p className="flex items-center gap-2"><House className="size-4 text-primary" />{asset.name}</p> : null}{maintenance ? <p className="flex items-center gap-2"><Wrench className="size-4 text-primary" />{maintenance.title}</p> : null}</div><p className="border-t pt-3 text-xs text-muted-foreground">Criado em {formatFinancialDate(transaction.createdAt.slice(0, 10))} · atualizado em {formatFinancialDate(transaction.updatedAt.slice(0, 10))}</p>
    {confirmingDelete ? <div className="rounded-lg border border-destructive/20 bg-destructive/5 p-4"><h3 className="font-display text-lg font-semibold">Excluir esta movimentação?</h3><p className="mt-1 text-sm text-muted-foreground">O registro financeiro será removido. Capítulos e outros registros relacionados não serão excluídos.</p><div className="mt-4 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onCancelDelete}>Cancelar</Button><Button type="button" variant="destructive" onClick={onDelete}>Excluir movimentação</Button></div></div> : <div className="flex flex-wrap gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={onEdit}><Edit3 /> Editar movimentação</Button><Button type="button" variant="ghost" className="text-destructive hover:bg-destructive/10 hover:text-destructive" onClick={onAskDelete}><Trash2 /> Excluir movimentação</Button></div>}
  </CardContent></Card>
}
export { TransactionDetails }
