import { Download, Edit3, FileCheck2, FileX2, FolderInput, Star, Trash2 } from 'lucide-react'
import { Link } from 'react-router'
import type { AppState } from '@/store/app-state'
import type { HouseDocument } from '@/domain/types'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { DocumentIcon } from '@/features/documents/components/DocumentIcon'
import { formatBytes, formatDocumentDate, getDocumentCategoryLabel, getDocumentFileTypeLabel } from '@/features/documents/presentation'

type Props = { item: HouseDocument; state: AppState; fileAvailable?: boolean; moving: boolean; confirmingDelete: boolean; onOpen: () => void; onDownload: () => void; onEdit: () => void; onToggleImportant: () => void; onStartMove: () => void; onCancelMove: () => void; onMove: (folderId: string | null) => void; onAskDelete: () => void; onCancelDelete: () => void; onDelete: () => void }

function DocumentDetails({ item, state, fileAvailable, moving, confirmingDelete, onOpen, onDownload, onEdit, onToggleImportant, onStartMove, onCancelMove, onMove, onAskDelete, onCancelDelete, onDelete }: Props) {
  const folder = state.documentFolders.find(candidate => candidate.id === item.folderId)
  const chapter = state.chapters.find(candidate => candidate.id === item.chapterId)
  const transaction = state.financialTransactions.find(candidate => candidate.id === item.financialTransactionId)
  return <Card className="shadow-book-sm"><CardHeader><CardTitle className="font-display text-lg">Detalhes do documento</CardTitle></CardHeader><CardContent className="space-y-4">
    <span className="flex size-11 items-center justify-center rounded-md bg-secondary text-primary"><DocumentIcon fileType={item.fileType} category={item.category} className="size-5" /></span>
    <div><p title={item.name} className="truncate text-sm font-medium">{item.name || 'Documento sem nome'}</p><p className="mt-1 text-xs text-muted-foreground">{item.description || 'Sem descrição.'}</p></div>
    <dl className="space-y-2 border-y py-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Categoria</dt><dd>{getDocumentCategoryLabel(item.category)}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Tipo e tamanho</dt><dd>{getDocumentFileTypeLabel(item.fileType)} · {formatBytes(item.sizeInBytes)}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Data</dt><dd>{formatDocumentDate(item.date)}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Pasta</dt><dd>{folder?.name ?? (item.folderId ? 'Pasta não disponível' : 'Sem pasta')}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Importância</dt><dd>{item.important ? 'Importante' : 'Normal'}</dd></div></dl>
    {chapter ? <p className="text-xs text-muted-foreground">Capítulo: <Link to={`/livro-da-casa/${chapter.id}`} className="text-primary hover:underline">{chapter.title}</Link></p> : item.chapterId ? <p className="text-xs text-muted-foreground">Capítulo relacionado não disponível</p> : null}
    {transaction ? <p className="text-xs text-muted-foreground">Movimentação: <Link to="/financeiro" className="text-primary hover:underline">{transaction.title}</Link></p> : item.financialTransactionId ? <p className="text-xs text-muted-foreground">Movimentação relacionada não disponível</p> : null}
    <p className="text-xs text-muted-foreground">Criado em {formatDocumentDate(String(item.createdAt).slice(0, 10))}<br/>Atualizado em {formatDocumentDate(String(item.updatedAt).slice(0, 10))}</p>
    <p className={`flex items-center gap-2 rounded-md bg-secondary/60 p-2.5 text-xs ${fileAvailable ? 'text-success' : 'text-muted-foreground'}`}>{fileAvailable ? <FileCheck2 className="size-4" aria-hidden="true"/> : <FileX2 className="size-4" aria-hidden="true"/>}{fileAvailable === undefined ? 'Verificando arquivo neste dispositivo…' : fileAvailable ? 'Arquivo disponível' : 'Arquivo não disponível neste dispositivo.'}</p>
    {moving ? <div className="rounded-lg border p-3"><label className="text-xs font-medium">Mover para</label><select defaultValue={item.folderId ?? ''} onChange={event => onMove(event.target.value || null)} className="mt-2 h-9 w-full rounded-lg border bg-card px-3 text-sm"><option value="">Sem pasta</option>{state.documentFolders.map(candidate => <option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select><Button type="button" variant="ghost" size="sm" className="mt-2" onClick={onCancelMove}>Cancelar</Button></div> : null}
    {confirmingDelete ? <div className="rounded-lg border border-destructive/20 bg-destructive/5 p-3"><h3 className="font-display text-base font-semibold">Excluir este documento?</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">O registro será removido do SIGA. Capítulos, movimentações e outros registros relacionados não serão excluídos.</p><div className="mt-3 flex justify-end gap-2"><Button type="button" variant="ghost" size="sm" onClick={onCancelDelete}>Cancelar</Button><Button type="button" variant="destructive" size="sm" onClick={onDelete}>Excluir documento</Button></div></div> : <div className="grid gap-2"><Button type="button" onClick={onOpen}>Abrir</Button><Button type="button" variant="outline" onClick={onDownload}><Download/>Baixar</Button><Button type="button" variant="outline" onClick={onEdit}><Edit3/>{fileAvailable ? 'Editar ou substituir arquivo' : 'Editar documento'}</Button><Button type="button" variant="ghost" onClick={onStartMove}><FolderInput/>Mover</Button><Button type="button" variant="ghost" onClick={onToggleImportant}><Star aria-hidden="true"/>{item.important ? 'Remover dos importantes' : 'Marcar como importante'}</Button><Button type="button" variant="ghost" className="text-destructive hover:bg-destructive/10 hover:text-destructive" onClick={onAskDelete}><Trash2 aria-hidden="true"/>Excluir</Button></div>}
  </CardContent></Card>
}
export { DocumentDetails }
